FROM j33f/node-docker-container:unoconv
MAINTAINER J33f <jeff@modulaweb.fr>

RUN set -x \
    apk update  \
    && apk upgrade  \
    && apk --no-cache add --virtual chrom \
    udev \
    nss \
    harfbuzz \
    ca-certificates \
    chromium \
    && npm install -g puppeteer@10.2.0
