FROM j33f/node-docker-container:latest
LABEL maintainer="J33f <jeff@modulaweb.fr>"

RUN set -x \
    apk update  \
    && apk upgrade  \
    && apk --no-cache add --virtual chrom \
    udev \
    ttf-freefont \
    ttf-droid-nonlatin \
    ttf-droid \
    ttf-dejavu \
    ttf-liberation \
    msttcorefonts-installer \
    fontconfig \
    freetype \
    nss \
    harfbuzz \
    ca-certificates \
    chromium \
    && npm install -g puppeteer@10.2.0

RUN update-ms-fonts && fc-cache -f
