FROM j33f/node-docker-container:unoconv
MAINTAINER J33f <jeff@modulaweb.fr>

RUN set -x \
    apk update  \
    && apk upgrade  \
    && apk --no-cache add --virtual chrom \
    udev ttf-freefont \
    && npm install -g puppeteer@12.0.1
