FROM j33f/node-docker-container:latest
LABEL maintainer="J33f <jeff@modulaweb.fr>"

ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

RUN set -x \
    apk update  \
    && apk upgrade  \
    && apk --no-cache add --virtual chrom \
    udev ttf-freefont chromium \
    && yarn global add puppeteer@1.10.0
