name: Automatic Build on Push and Schedule

on:
  push:
    branches:
      - master
      - pupeteer
      - unoconv
      - pupeteer-unoconv
    paths-ignore:
      - 'Readme.md'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: j33f/node-docker-container:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: j33f/node-docker-container
          readme-filepath: ./Readme.md
          short-description: 'Improved node lts-alpine image with variants including pupeteer and unoconv'

  docker-pupeteer:
    needs: docker-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.pupeteer
          push: true
          tags: j33f/node-docker-container:pupeteer

  docker-unoconv:
    needs: docker-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.unoconv
          push: true
          tags: j33f/node-docker-container:unoconv

  docker-pupeteer-unoconv:
    needs: docker-unoconv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.pupeteer-unoconv
          push: true
          tags: j33f/node-docker-container:pupeteer-unoconv

  update-readme:
    needs:
      - docker-latest
      - docker-unoconv
      - docker-pupeteer
      - docker-pupeteer-unoconv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Put Current Date on Readme.md
        run: |
          d=$(date +%F); sed -r "s/[012]{4}[-\/][0-9]{2}[-\/][0-9]{2}/$d/g" ./Readme.md > ./tmp && cat ./tmp > ./Readme.md && rm ./tmp

      - name: Push to master
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Change last built date'
          add: 'Readme.md'
          default_author: github_actions
